export default function getKeyName(key) {
  switch (key) {
    case 'Meta':
      return 'Cmd';
    case 'Dead':
      return '^';
    case '«':
      return 'q';
    case '»':
      return 'q';
    case '„':
      return 'w';
    case '∑':
      return 'w';
    case '‰':
      return 'e';
    case '€':
      return 'e';
    case '¸':
      return 'r';
    case '®':
      return 'r';
    case '˝':
      return 't';
    case '†':
      return 't';
    case 'ˇ':
      return 'z';
    case 'Ω':
      return 'z';
    case 'Á':
      return 'u';
    case '¨':
      return 'u';
    case 'Û':
      return 'i';
    case '⁄':
      return 'i';
    case 'Ø':
      return 'o';
    case 'ø':
      return 'o';
    case '∏':
      return 'p';
    case '•':
      return 'p';
    case '°':
      return 'ü';
    case '':
      return '+';
    case '±':
      return '+';
    case 'Å':
      return 'a';
    case 'å':
      return 'a';
    case 'Í':
      return 's';
    case '‚':
      return 's';
    case '™':
      return 'd';
    case '∂':
      return 'd';
    case 'Ï':
      return 'f';
    case 'ƒ':
      return 'f';
    case 'Ì':
      return 'g';
    case '©':
      return 'g';
    case 'ı':
      return 'j';
    case 'º':
      return 'j';
    case 'ˆ':
      return 'k';
    case '∆':
      return 'k';
    case '@':
      return 'l';
    case 'ﬂ':
      return 'l';
    case 'Œ':
      return 'ö';
    case 'œ':
      return 'ö';
    case 'Æ':
      return 'ä';
    case 'æ':
      return 'ä';
    case '’':
      return '#';
    case '‘':
      return '#';
    case '≥':
      return '<';
    case '≤':
      return '<';
    case '‡':
      return 'y';
    case '¥':
      return 'y';
    case 'Ù':
      return 'x';
    case '≈':
      return 'x';
    case 'Ç':
      return 'c';
    case 'ç':
      return 'c';
    case '◊':
      return 'v';
    case '√':
      return 'v';
    case '‹':
      return 'b';
    case '∫':
      return 'b';
    case '›':
      return 'n';
    case '~':
      return 'n';
    case '˘':
      return 'm';
    case 'µ':
      return 'm';
    case '˛':
      return ',';
    case '∞':
      return ',';
    case '÷':
      return '.';
    case '…':
      return '.';
    case '—':
      return '-';
    case '–':
      return '-';
    case ' ':
      return 'Space';
    default:
      return key;
  }
}
